### ISSUE TITLE
How to use Microsoft GraphRAG and llm-graph-builder together?

### ISSUE THREAD

**Issue by crazyyanchao** [neo4j-labs/llm-graph-builder#511]

**Comment by nileshtrivedi** [comment]
Has anyone compared Microsoft GraphRAG and Neo4j's GraphRAG approaches? How do they differ?

**Comment by crazyyanchao** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by crazyyanchao** [comment]
@nileshtrivedi I think the main difference is the global-search, llm-graph-builder doesn't seem to have a way to do community summaries.

**Comment by jexp** [comment]
We are planning to integrate GraphRAG aspects, like generating communities between entities and generating community summaries and also adding global and local search that takes them into account. In the next version we'll be able to generate entity embeddings already.

@tomasonjo has written an awesome blog post if you want to do this in  your own code.
https://medium.com/@bratanic-tomaz/implementing-from-local-to-global-graphrag-with-neo4j-and-langchain-73924cc5bab4

**Comment by nileshtrivedi** [comment]
It would be amazing to have [Microsoft GraphRAG library](https://microsoft.github.io/graphrag/posts/get_started/) included directly and used in the llm-graph-builder app (rather than re-implementing the features). This would allow continuous improvements in that library to easily be available to this app. They are also [working on improving the support for Neo4J](https://github.com/microsoft/graphrag/issues/433). But this might require a major effort.

**Comment by nileshtrivedi** [comment]
@jexp Would you be able to share a summary of the changes that have happened since your message in July and the current status?
