### ISSUE TITLE
Neo4j Instance

### ISSUE THREAD

**Issue by KmlNzrl** [neo4j-labs/llm-graph-builder#759]
Hello,

I have a question, is it possible to use "neo4j://localhost:7687", which is the one that can be accessed by "http://localhost:7474/browser/" instead of using the Neo4j Instance? This is because I was thinking to run the app and maintain it locally without any cloud.

I hope my question can be understand. Thank you

**Comment by kartikpersistent** [comment]
Hi @KmlNzrl It is not possible

**Comment by KmlNzrl** [comment]
i see, therefore i assume that the neo4j instance is a must in order to successfully run the graph builder

**Comment by kartikpersistent** [comment]
yes

**Comment by mystvearn** [comment]
@KmlNzrl If you run lllm-graph-builder on your own machine using docker then yes it would be possible to connect to local Neo4j DB as well. In this case, instead of using **"neo4j://localhost:7687"** use **"neo4j://host.docker.internal:7687"**

Another advantage is that you can customize the embedding function or add in new GPT model on your own.
