### ISSUE TITLE
Can not connect to neo4j

### ISSUE THREAD

**Issue by PP7364** [neo4j-labs/llm-graph-builder#802]
Why does the front-end connet to neo4j prompt “Network Error”   thank you for advice
![Network Error](https://github.com/user-attachments/assets/9408da50-44e3-4bce-9f40-e1bd026b2fcc)

**Comment by naveen-420** [comment]
+1

**Comment by kartikpersistent** [comment]
Hi @PP7364  can you share more details from where you are running the llm graph builder on hosted version/local if local which branch you are using? which config?

**Comment by PP7364** [comment]
I deployed with docker and used the command “docker-compoes up -d” to start the container and the result is shown below (not sure if this is correct).
![1](https://github.com/user-attachments/assets/21badbb3-62f1-48bc-97c6-fd26b8b131d1)

Some details：
My computer's port 8000 is occupied, so I changed the port from “8000:8000” to “8001:8001” in docker-compose.yml, will this change affect the result

**Comment by PP7364** [comment]
I made it work successfully using the Development (Separate Frontend and Backend), but I still want to know what was wrong with that before.

**Comment by kartikpersistent** [comment]
can you share the error details like network logs, console message you received earlier? so that we can help with that otherwise you can close this issue

**Comment by PP7364** [comment]
Thank you for your help

**Comment by gschmutz** [comment]
I had the same problem (`Network error`) when trying to connect to Neo4J. I have also changed the port of the backend service from 8000 to 28414 (due to port conflicts). 

To avoid the error, you have to change the `VITE_BACKEND_API_URL` environment variable to

`VITE_BACKEND_API_URL="http://localhost:28414"`

But this will only have an effect at built-time of the image. If you build and push the docker image with the default and try to set the environment variable at runtime (when starting the container), it will not work!

**Comment by PP7364** [comment]
I get it! I think I have not changed the VITE_BACKEND_API_URL environment variable correctly. I will try this solution!
Thanks! 
Happy New Year!😁😁😁
