### ISSUE TITLE
Backend does not pass neo4J credentials to Frontend ?

### ISSUE THREAD

**Issue by markNZed** [neo4j-labs/llm-graph-builder#826]
When viewing the frontend I get a popup asking for neo4j database connection information but the backend is already configured with this so I do not expect the user to enter that information. Have I misconfigured or is the idea to have the user of the frontend know the login information of the neo4j DB used by the backend ? Thanks

**Comment by aashipandya** [comment]
Neo4j database Connection created from frontend will be used for processing of any source.

**Comment by markNZed** [comment]
@kartikpersistent I hope you mean remove any use of the DB credentials in the frontend. Is there a particular developer setup you can recommend ? I would like to be able to make changes to the frontend code and have the UI update automatically and I would like to have source maps to be able to debug the javascript in the frontend.

**Comment by kartikpersistent** [comment]
Hi @markNZed I meat we will remove neo4j credentials env variables from backend environment in future

**Comment by markNZed** [comment]
That creates quite a barrier to demoing as people will expect  a chat-like interface. Why not route the requests to neo4j through the backend (like the LLM). I guess you see why it would not be a good idea to put LLM API keys into the frontend but it is unclear to me why it is a good idea to put DB keys into the frontend.

**Comment by jexp** [comment]
Actually, let's discuss this, the original idea was that e.g. team or department can configure the backend to talk to their database. And then the front-end users don't have to provide credentials.

For the publicly hosted variant that's not required but for private hosting it would be really useful, so let's not remove the feature but rather adjust it so that when the backend is configured, the front end can rely on that back-end information for connection credentials.
@karanchellani please capture.

**Comment by praveshkumar1988** [comment]
Endpoint created and committed in DEV
