### ISSUE TITLE
LLM env vars not found, like LLM_MODEL_CONFIG_openai_gpt_3.5

### ISSUE THREAD

**Issue by ocbreulmann** [neo4j-labs/llm-graph-builder#893]
I have configured in my .env in the root folder which models to use and put the OPENAI_API_KEY in there. I get this error message on the console if any model is required (for example when trying to read the schema from some text): 

```
backend   | 2024-11-21 11:29:41,582 - Schema result from DB: [{'labels': ['Document'], 'relationshipTypes': []}]
backend   | 2024-11-21 11:29:44,842 - Model: LLM_MODEL_CONFIG_openai_gpt_3.5
backend   | 2024-11-21 11:29:44,843 - Exception in getting the schema from text:'NoneType' object has no attribute 'split'
backend   | Traceback (most recent call last):
backend   |   File "/code/score.py", line 676, in populate_graph_schema
backend   |     result = populate_graph_schema_from_text(input_text, model, is_schema_description_checked)
backend   |   File "/code/src/main.py", line 702, in populate_graph_schema_from_text
backend   |     result = schema_extraction_from_text(text, model, is_schema_description_cheked)
backend   |   File "/code/src/shared/schema_extraction.py", line 31, in schema_extraction_from_text
backend   |     llm, model_name = get_llm(model)
backend   |   File "/code/src/llm.py", line 48, in get_llm
backend   |     model_name, api_key = env_value.split(",")
backend   | AttributeError: 'NoneType' object has no attribute 'split'
```

It seems that usually env vars are being constructed by the solution within the docker instance automatically based on the local .env and this seems to fail? 

Any idea what could cause this?

**Comment by MelvinAkothINGUBU** [comment]
To resolve the issue, update the get_llm(model: str) function in llm.py as follows:

Change this line:

env_key = "LLM_MODEL_CONFIG_" + model

to:

env_key = "LLM_MODEL_CONFIG_" + model.replace("-", "_")

The issue arises due to a mismatch between hyphens (-) and underscores (_) in the environment variable names.

Additionally, ensure the API key values are correctly set in your environment file on the backend. The format should look like this:

LLM_MODEL_CONFIG_openai_gpt_3_5="gpt-3.5-turbo-0125,sk-*******"
LLM_MODEL_CONFIG_openai_gpt_4o="gpt-4o-mini-2024-07-18,sk-*******"

This is in addition to setting your OpenAI API key at the very top of the backend env file

This resolved the problem in my setup :)

**Comment by ocbreulmann** [comment]
Thanks! I actually tried this but it did not solve it. I am just hardcoding the values in the get_llm() function now. Fine for me. No time to debug it.
