### ISSUE TITLE
Backticks in database name not supported

### ISSUE THREAD

**Issue by michela** [neo4j-labs/llm-graph-builder#937]
An equivalent function to handle_backticks_nodes_relationship_id_type for database names

e.g. handle_backticks_database_name

would be useful. 

This is a limitation of langchain-neo4j and a pain given it's not a quick action to rename Neo4j databases

https://github.com/langchain-ai/langchain-neo4j/issues/22

**Comment by kaustubh-darekar** [comment]
Hi @michela,

We attempted to replicate the problem using a Neo4j database with a hyphen in its name (e.g., major-minor) and tried connecting to it using the langchain-neo4j library with the parameters you mentioned. However, we were unable to reproduce the issue on our end; the connection worked as expected.

Here are a few things to double-check on your side:
1. Database Name: Is it "major-minor" or any other special character/symbol included?
2. Library Version: 0.1.1

If the issue persists, could you provide more details such as:
• The langchain-neo4j versions you’re using.
• The full error message (if any) you’re encountering.
• Any additional steps or configurations in your setup.
This will help us investigate further and pinpoint the root cause.
Looking forward to your response.

**Comment by michela** [comment]
This seems to work fine now. Might have been operator error. Thanks!
